dist: bionic
sudo: false

language: cpp

addons:
  apt:
    update: true
    packages:
      - build-essenial
      - clang-6.0
      - autoconf
      - automake
      - bison
      - expect
      - libevent-dev
      - libmysqlclient-dev
      - libpcre3-dev
      - libpq-dev
      - libsqlite3-dev
      - libssl-dev
      - libtool
      - libz-dev
      - telnet
      - libgtest-dev

script: bash -x ./.travis_build.sh

after_failure:
    - echo src/thirdparty/jemalloc/config.log
    - cat src/thirdparty/jemalloc/config.log
    - echo =================================
    - echo build/config.log
    - cat build/config.log
    - echo =================================
    - echo -n 50 src/testsuite/log/*
    - tail -n 50 src/testsuite/log/*

compiler:
  - gcc

env:
# clang builds
  - BUILD="x86_64" COMPILER="clang" COMPILER_FLAGS="-m64 -mtune=generic" TYPE="develop" CONFIG="testdev"
  - BUILD="x86_64" COMPILER="clang" COMPILER_FLAGS="-m64 -mtune=generic" TYPE=""        CONFIG="testrelease"
# gcc builds
  - BUILD="x86_64" COMPILER="gcc" COMPILER_FLAGS="-m64 -mtune=generic" TYPE="develop" CONFIG="testdev" GCOV="yes"
  - BUILD="x86_64" COMPILER="gcc" COMPILER_FLAGS="-m64 -mtune=generic" TYPE=""        CONFIG="testrelease"
# coverity
  - BUILD="x86_64" COMPILER="gcc" COMPILER_FLAGS="-m64 -mtune=generic" TYPE="develop" CONFIG="testdev" COVERITY="yes"
